### ISSUE TITLE
大哥开源吧，丰富下社区。

### ISSUE THREAD

**Issue by ck76** [flutterchina/gitme#10]
开源了star肯定涨的快。。。

**Comment by VectorWen** [comment]
![image](https://user-images.githubusercontent.com/6134525/47421357-faff8380-d7b2-11e8-8d80-d406a62a9868.png)
如何压缩apk到那么小的呀？开源一下呗。我写个HelloWorld 打包的APK 就 > 25M

**Comment by infinite2009** [comment]
一直都搞不懂flutter app到底怎么布局，动不动overflow，滚动还不能里边嵌套ListView，想学习下gitme，结果不开源，唉
