### ISSUE TITLE
一个真心希望Gitme开源的前端开发者

### ISSUE THREAD

**Issue by vfiee** [flutterchina/gitme#34]
@wendux  希望能尽早开源出来，给我们一个标准，这样既丰富了Fluuter社区，也支持了开源力量。我相信作者为Flutter开源社区做出的贡献是巨大的，我们是真心的喜欢gitme应用，同时也迫切的希望作者能将gitme源码开源出来，供大家学习交流。每次看到gitme项目的start都心急火燎（作者说过3000star开源），希望大家支持作者，支持开源，支持Flutter。看到的希望点击右上角start，谢谢。

**Comment by aarontang22** [comment]
项目不开源，不知道丢到github上什么意思。

**Comment by kaige-cai** [comment]
原来是个空壳儿,白高兴一场。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
