### ISSUE TITLE
动态tab 长列表(下拉较多)， 切换时有明显的卡顿

### ISSUE THREAD

**Issue by etoah** [flutterchina/gitme#5]
动态tab 长列表(下拉较多)， 切换时有明显的卡顿， 试过native在长列表表现很好， 没有卡顿， 是flutter没有做优化的原因吗

**Comment by wendux** [comment]
并没有用webview, 
 flutter tabview中每次切换tab都会重新创建tab, 所以我们必须保存tab页列表的滚动位置，当tab页列表非常长时，切换之后，原来滚动位置之上的列表项都要重新build，这就产生了性能问题，为了保存滚动位置，目前没有什么好的解决方式


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wendux** [comment]
最新同步，此问题已在当前开发版本中解决，敬请关注gitme版本更新。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by etoah** [comment]
感谢
