### ISSUE TITLE
无法登陆GitHub账号

### ISSUE THREAD

**Issue by Megrax** [flutterchina/gitme#66]
密码确保正确，用户名使用了GitHub的ID，但是仍然提示账户或密码错误。

**Comment by anchuanyuan** [comment]
我也是,在电脑端能登陆 app登录不上,

**Comment by Megrax** [comment]
> 我也是,在电脑端能登陆 app登录不上,

才看到readme.md，原来是停止维护了:(

**Comment by Sky24n** [comment]
仿gitme，仅安卓。[链接](https://github.com/Sky24n/Moss)
