### ISSUE TITLE
你们dio库是怎么封装的？

### ISSUE THREAD

**Issue by cikichen** [flutterchina/gitme#7]
dio网络库。

**Comment by wendux** [comment]
@cikichen https://github.com/flutterchina/dio


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by cikichen** [comment]
@wendux 可能表达不准确，我的意思是dio的工具类封装

**Comment by wendux** [comment]
创建一个全局dio单例，所有请求都通过这个单例来发送


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
